import type { InteractiveLessonDefinition } from "./types";

export const POLYGON_ANGLES_LESSON_ID = "l-mm6el08l";

export const polygonAnglesLesson: InteractiveLessonDefinition = {
  id: POLYGON_ANGLES_LESSON_ID,
  version: 2,
  slug: "polygon-angles",
  title: "زوايا المضلع",
  stage: "المرحلة الثانوية",
  grade: "الصف الأول الثانوي",
  subject: "الرياضيات",
  unit: "الأشكال الرباعية",
  estimatedMinutes: 22,
  introduction: {
    heading: "نحوّل المضلع إلى مثلثات نعرفها",
    paragraphs: [
      "المضلع شكل مغلق مكوّن من أضلاع مستقيمة، مثل المثلث والرباعي والخماسي.",
      "بدل أن نحفظ مجموع زوايا كل شكل، نرسم خطوطًا من رأس واحد فنقسّم المضلع إلى مثلثات. ثم نجمع 180° مرة لكل مثلث.",
    ],
    foundationSteps: [
      {
        title: "ابدأ من حقيقة تعرفها",
        description: "مجموع الزوايا الداخلية لأي مثلث يساوي 180°، لذلك سنستخدم المثلث كوحدة بناء.",
      },
      {
        title: "قسّم من رأس واحد",
        description: "اختر رأسًا واحدًا وارسم منه الأقطار إلى الرؤوس غير المجاورة. لن تتداخل المثلثات ولن تترك فراغًا.",
      },
      {
        title: "عدّ المثلثات ثم اجمع",
        description: "عدد المثلثات يكون أقل من عدد الأضلاع باثنين، ثم نضرب هذا العدد في 180°.",
      },
    ],
    examples: [
      { label: "مثلث", sides: 3, triangles: 1, angleSum: 180 },
      { label: "رباعي", sides: 4, triangles: 2, angleSum: 360 },
      { label: "خماسي", sides: 5, triangles: 3, angleSum: 540 },
    ],
    takeaway: "كلما أضفنا ضلعًا ظهر مثلث جديد. لذلك يكون عدد المثلثات n - 2، وفي بقية الرحلة ستثبت هذه الفكرة بالرسم والحركة والاختيار.",
    formula: {
      expression: "S = (n - 2) \\times 180^\\circ",
      label: "مجموع الزوايا الداخلية يساوي عدد الأضلاع ناقص اثنين، مضروبًا في مئة وثمانين درجة",
      parts: [
        { symbol: "S", meaning: "مجموع الزوايا الداخلية" },
        { symbol: "n", meaning: "عدد أضلاع المضلع" },
        { symbol: "n - 2", meaning: "عدد المثلثات الناتجة من رأس واحد" },
        { symbol: "180°", meaning: "مجموع زوايا مثلث واحد" },
      ],
    },
    workedExample: {
      title: "مثال سريع: الخماسي",
      steps: ["عدد الأضلاع n = 5", "عدد المثلثات 5 - 2 = 3", "نجمع 180° ثلاث مرات"],
      result: "3 × 180° = 540°",
    },
    commonMistake: {
      wrong: "5 × 180°",
      correction: "لا نضرب عدد الأضلاع مباشرة. الخماسي ينقسم إلى 3 مثلثات، لذلك نستخدم (5 - 2) × 180°.",
    },
  },
  objectives: [
    "أفسّر لماذا يمكن تقسيم المضلع من رأس واحد إلى مثلثات.",
    "أستنتج قانون مجموع الزوايا الداخلية وأستخدمه.",
    "أحسب زاوية مجهولة داخل مضلع.",
    "أميّز العلاقة بين الزوايا الداخلية والخارجية.",
  ],
  skills: [
    {
      id: "triangle-angle-sum",
      title: "مجموع زوايا المثلث",
      shortTitle: "أساس المثلث",
      description: "يعرف أن مجموع الزوايا الداخلية لأي مثلث يساوي 180°.",
    },
    {
      id: "polygon-triangulation",
      title: "تقسيم المضلع إلى مثلثات",
      shortTitle: "تقسيم المضلع",
      description: "يربط عدد أضلاع المضلع بعدد المثلثات الناتجة من رأس واحد.",
    },
    {
      id: "interior-angle-formula",
      title: "استخدام قانون مجموع الزوايا",
      shortTitle: "تطبيق القانون",
      description: "يستخدم (n - 2) × 180° بصورة صحيحة.",
    },
    {
      id: "unknown-angle",
      title: "حساب زاوية مجهولة",
      shortTitle: "الزاوية المجهولة",
      description: "يستعمل مجموع زوايا المضلع لإيجاد قياس زاوية مفقودة.",
    },
    {
      id: "exterior-angles",
      title: "الزوايا الخارجية",
      shortTitle: "الخارجية",
      description: "يعرف أن مجموع زاوية خارجية واحدة عند كل رأس يساوي 360°.",
    },
  ],
  questions: [
    {
      id: "warmup-triangle",
      skillId: "triangle-angle-sum",
      type: "multiple_choice",
      prompt: "لتثبيت أساس الدرس: كم مجموع زوايا المثلث الداخلية؟",
      options: [
        { id: "180", label: "180°" },
        { id: "360", label: "360°" },
        { id: "90", label: "90°" },
        { id: "unknown", label: "لا أعرف" },
      ],
      correctAnswer: "180",
      hints: [
        "تخيّل زوايا مثلث ورقي بعد قصّها ووضعها بجانب بعضها على خط مستقيم.",
        "الخط المستقيم قياسه 180°، وزوايا المثلث الثلاث تكوّنه معًا.",
      ],
      correctFeedback: "ممتاز. هذه الـ 180° ستكون القطعة التي سنبني بها قانون المضلعات.",
      defaultIncorrectFeedback: "لنثبّت الأساس أولًا: زوايا المثلث الثلاث تكوّن زاوية مستقيمة.",
      errorPatterns: [
        { answers: [360], feedback: "360° هي دورة كاملة. أمّا زوايا المثلث فتجتمع على خط مستقيم." },
        { answers: [90], feedback: "90° قد تكون زاوية واحدة قائمة، وليست مجموع زوايا المثلث." },
        { answers: ["unknown"], feedback: "لا بأس. اجمع زوايا أي مثلث تعرفه؛ مثل 90° + 60° + 30°." },
      ],
    },
    {
      id: "hexagon-triangles",
      skillId: "polygon-triangulation",
      type: "multiple_choice",
      prompt: "إذا تكوّن الخماسي من 3 مثلثات عند تقسيمه من رأس واحد، فكم مثلثًا يتكوّن داخل سداسي؟",
      options: [
        { id: "3", label: "3 مثلثات" },
        { id: "4", label: "4 مثلثات" },
        { id: "5", label: "5 مثلثات" },
        { id: "6", label: "6 مثلثات" },
      ],
      correctAnswer: "4",
      hints: [
        "جرّب زيادة ضلع واحد على الخماسي ولاحظ كم مثلثًا جديدًا يظهر.",
        "عدد المثلثات أقل من عدد الأضلاع بمقدار 2.",
      ],
      correctFeedback: "صحيح: السداسي ينقسم إلى 4 مثلثات، أي 6 - 2.",
      defaultIncorrectFeedback: "عدّ المناطق المثلثة الناتجة من الخطوط الخارجة من رأس واحد فقط.",
      errorPatterns: [
        { answers: [6], feedback: "استخدمت عدد الأضلاع مباشرة. الخماسي له 5 أضلاع لكنه انقسم إلى 3 مثلثات؛ ما العلاقة بين 5 و3؟" },
        { answers: [3], feedback: "هذا عدد مثلثات الخماسي. السداسي يضيف ضلعًا ومنطقة مثلثة جديدة." },
        { answers: [5], feedback: "الخطوط كلها تبدأ من رأس واحد، لذلك لا نحصل على مثلث بعدد الأضلاع." },
      ],
    },
    {
      id: "explain-minus-two",
      skillId: "polygon-triangulation",
      type: "multiple_choice",
      prompt: "اختر التفسير الأدق: لماذا يظهر العدد 2 في القانون n - 2؟",
      helperText: "اختر الفكرة المرتبطة بالتقسيم من رأس واحد.",
      options: [
        { id: "adjacent", label: "لأن الضلعين المجاورين للرأس المختار يحدّان الشكل ولا يصنعان مثلثين إضافيين" },
        { id: "even", label: "لأن عدد أضلاع كل مضلع عدد زوجي" },
        { id: "two-angles", label: "لأن كل مثلث يحتوي زاويتين فقط" },
        { id: "half", label: "لأننا نقسم عدد الأضلاع على النصف" },
      ],
      correctAnswer: "adjacent",
      hints: [
        "قارن: المثلث 3 ← 1، الخماسي 5 ← 3، السداسي 6 ← 4.",
        "من الرأس الذي اخترناه، الضلعان المجاوران له يحدّان الشكل ولا يصنعان مثلثين إضافيين.",
      ],
      correctFeedback: "تفسير ممتاز: التقسيم من رأس واحد ينتج دائمًا مثلثين أقل من عدد الأضلاع.",
      defaultIncorrectFeedback: "اقتربت. اذكر العلاقة بين عدد الأضلاع وعدد المثلثات الناتجة من رأس واحد.",
    },
    {
      id: "choose-four-triangle-shape",
      skillId: "polygon-triangulation",
      type: "multiple_choice",
      prompt: "أي شكل ينقسم من رأس واحد إلى 4 مثلثات؟",
      helperText: "اختر الرسم المناسب؛ الخطوط البرتقالية توضح التقسيم.",
      options: [
        { id: "pentagon", label: "خماسي", visual: { kind: "polygon", sides: 5, split: true } },
        { id: "hexagon", label: "سداسي", visual: { kind: "polygon", sides: 6, split: true } },
        { id: "heptagon", label: "سباعي", visual: { kind: "polygon", sides: 7, split: true } },
        { id: "octagon", label: "ثماني", visual: { kind: "polygon", sides: 8, split: true } },
      ],
      correctAnswer: "hexagon",
      hints: [
        "ابحث عن شكل عدد أضلاعه أكبر من عدد المثلثات باثنين.",
        "4 مثلثات تعني 4 + 2 = 6 أضلاع.",
      ],
      correctFeedback: "صحيح. السداسي ينقسم إلى 4 مثلثات لأن 6 - 2 = 4.",
      defaultIncorrectFeedback: "عدّ المناطق المثلثة في الرسم، أو أضف 2 إلى عدد المثلثات المطلوبة.",
    },
    {
      id: "heptagon-sum",
      skillId: "interior-angle-formula",
      type: "multiple_choice",
      prompt: "سباعي الأضلاع: كم مجموع زواياه الداخلية؟",
      options: [
        { id: "540", label: "540°" },
        { id: "720", label: "720°" },
        { id: "900", label: "900°" },
        { id: "1260", label: "1260°" },
      ],
      correctAnswer: "900",
      hints: [
        "السباعي له n = 7. ابدأ بحساب n - 2.",
        "5 × 180° = ؟",
      ],
      correctFeedback: "أحسنت: (7 - 2) × 180° = 900°.",
      defaultIncorrectFeedback: "اكتب القانون أولًا، ثم عوّض عن n بعدد الأضلاع.",
      errorPatterns: [
        { answers: [1260], feedback: "ضربت 7 × 180 مباشرة. عدد المثلثات ليس 7؛ اطرح 2 أولًا." },
        { answers: [720], feedback: "استخدمت 4 مثلثات، وهذا يناسب السداسي. السباعي ينقسم إلى 5 مثلثات." },
        { answers: [540], feedback: "540° مجموع زوايا الخماسي. راجع عدد أضلاع السباعي." },
      ],
    },
    {
      id: "formula-order",
      skillId: "interior-angle-formula",
      type: "ordering",
      prompt: "رتّب خطوات حساب مجموع زوايا أي مضلع.",
      options: [
        { id: "identify", label: "أحدّد عدد الأضلاع n" },
        { id: "subtract", label: "أحسب عدد المثلثات n - 2" },
        { id: "multiply", label: "أحوّل المثلثات إلى درجات: × 180°" },
      ],
      correctAnswer: ["identify", "subtract", "multiply"],
      hints: [
        "لا تستطيع التعويض قبل أن تعرف n.",
        "الضرب في 180° هو الخطوة الأخيرة بعد معرفة عدد المثلثات.",
      ],
      correctFeedback: "ترتيب صحيح: حدّد n، ثم اطرح 2، ثم اضرب في 180°.",
      defaultIncorrectFeedback: "ابدأ بالمعلومة التي يعطيها شكل المضلع، وأنهِ بتحويل عدد المثلثات إلى درجات.",
    },
    {
      id: "missing-angle",
      skillId: "unknown-angle",
      type: "multiple_choice",
      prompt: "رباعي زواياه 135° و90° و90° وزاوية مجهولة. أوجد الزاوية المجهولة.",
      options: [
        { id: "45", label: "45°" },
        { id: "90", label: "90°" },
        { id: "135", label: "135°" },
        { id: "315", label: "315°" },
      ],
      correctAnswer: "45",
      hints: [
        "مجموع زوايا الرباعي 360°.",
        "اجمع الزوايا المعروفة ثم اطرح المجموع من 360°.",
      ],
      correctFeedback: "صحيح: 360° - (135° + 90° + 90°) = 45°.",
      defaultIncorrectFeedback: "لا تقسّم المجموع بالتساوي؛ هذا الرباعي غير منتظم. اطرح الزوايا المعروفة من 360°.",
      errorPatterns: [
        { answers: [90], feedback: "افترضت أن الزاوية قائمة. اجمع القيم المعطاة أولًا؛ المتبقي ليس 90°." },
        { answers: [315], feedback: "315° هو مجموع الزوايا المعروفة، والمطلوب هو المتبقي من 360°." },
      ],
    },
    {
      id: "exterior-sum",
      skillId: "exterior-angles",
      type: "true_false",
      prompt: "صح أم خطأ: مجموع زاوية خارجية واحدة عند كل رأس لأي مضلع محدب يساوي 360°.",
      options: [
        { id: "true", label: "صح" },
        { id: "false", label: "خطأ" },
      ],
      correctAnswer: true,
      hints: ["تخيّل أنك تمشي حول المضلع وتدور عند كل رأس حتى تعود لاتجاهك الأول."],
      correctFeedback: "صحيح. دورة كاملة حول المضلع تساوي 360°.",
      defaultIncorrectFeedback: "تتبّع مقدار دورانك أثناء المشي حول المضلع؛ عند العودة تكون قد أتممت دورة كاملة.",
    },
    {
      id: "assessment-triangle",
      skillId: "triangle-angle-sum",
      type: "multiple_choice",
      prompt: "مثلث فيه زاويتان 65° و45°. ما قياس الزاوية الثالثة؟",
      options: [
        { id: "60", label: "60°" },
        { id: "65", label: "65°" },
        { id: "70", label: "70°" },
        { id: "80", label: "80°" },
      ],
      correctAnswer: "70",
      hints: [],
      correctFeedback: "صحيح.",
      defaultIncorrectFeedback: "اطرح مجموع الزاويتين من 180°.",
    },
    {
      id: "assessment-octagon-triangles",
      skillId: "polygon-triangulation",
      type: "multiple_choice",
      prompt: "كم مثلثًا ينتج عند تقسيم مضلع ثماني من رأس واحد؟",
      options: [
        { id: "5", label: "5 مثلثات" },
        { id: "6", label: "6 مثلثات" },
        { id: "7", label: "7 مثلثات" },
        { id: "8", label: "8 مثلثات" },
      ],
      correctAnswer: "6",
      hints: [],
      correctFeedback: "صحيح.",
      defaultIncorrectFeedback: "قارن عدد الأضلاع بعدد المثلثات الناتجة من رأس واحد.",
      errorPatterns: [{ answers: [8], feedback: "استخدمت عدد الأضلاع نفسه. تذكّر أن عدد المثلثات أقل بمقدار 2." }],
    },
    {
      id: "assessment-dodecagon",
      skillId: "interior-angle-formula",
      type: "multiple_choice",
      prompt: "ما مجموع الزوايا الداخلية لمضلع ذي 12 ضلعًا؟",
      options: [
        { id: "1440", label: "1440°" },
        { id: "1800", label: "1800°" },
        { id: "1980", label: "1980°" },
        { id: "2160", label: "2160°" },
      ],
      correctAnswer: "1800",
      hints: [],
      correctFeedback: "صحيح.",
      defaultIncorrectFeedback: "راجع تطبيق القانون (n - 2) × 180°.",
      errorPatterns: [{ answers: [2160], feedback: "استعملت n × 180° ولم تطرح 2." }],
    },
    {
      id: "assessment-missing-angle",
      skillId: "unknown-angle",
      type: "multiple_choice",
      prompt: "خماسي مجموع أربع من زواياه 430°. ما قياس الزاوية الخامسة؟",
      options: [
        { id: "90", label: "90°" },
        { id: "100", label: "100°" },
        { id: "110", label: "110°" },
        { id: "430", label: "430°" },
      ],
      correctAnswer: "110",
      hints: [],
      correctFeedback: "صحيح.",
      defaultIncorrectFeedback: "احسب مجموع زوايا الخماسي أولًا، ثم اطرح 430°.",
      errorPatterns: [{ answers: [970], feedback: "طرحت بالاتجاه العكسي. الزاوية المجهولة هي المتبقي من 540°." }],
    },
    {
      id: "assessment-nonagon-exterior",
      skillId: "exterior-angles",
      type: "multiple_choice",
      prompt: "ما قياس الزاوية الخارجية الواحدة لتساعي منتظم؟",
      options: [
        { id: "30", label: "30°" },
        { id: "40", label: "40°" },
        { id: "45", label: "45°" },
        { id: "50", label: "50°" },
      ],
      correctAnswer: "40",
      hints: [],
      correctFeedback: "صحيح.",
      defaultIncorrectFeedback: "اقسم 360° على عدد الأضلاع في المضلع المنتظم.",
    },
  ],
  steps: [
    {
      id: "goals",
      type: "objectives",
      eyebrow: "شرح الدرس",
      title: "افهم الفكرة قبل أن تجيب",
      tutorMessage: "هذه الخطوة للشرح فقط، ولا يوجد فيها سؤال. اقرأ الفكرة وشاهد كيف يتحول المضلع إلى مثلثات.",
    },
    {
      id: "video-summary",
      type: "video",
      eyebrow: "الشرح المرئي",
      title: "شاهد الفكرة وهي تتحرك",
      tutorMessage: "بعد أن أخذت الصورة الأساسية، شاهد الشرح المرئي. ركّز على الخطوط الخارجة من رأس واحد وعدد المثلثات الناتجة.",
    },
    {
      id: "warmup",
      type: "warmup",
      eyebrow: "تحقق بصري سريع",
      title: "ثبّت الفكرة الأساسية",
      tutorMessage: "لا كتابة هنا. اختر ما يطابق الشرح الذي شاهدته، وسأوضح لك سبب أي خطأ.",
      questionIds: ["warmup-triangle", "explain-minus-two"],
    },
    {
      id: "discover",
      type: "polygon_discovery",
      eyebrow: "مختبر الأشكال",
      title: "قسّم وشاهد ثم اختر",
      tutorMessage: "غيّر عدد الأضلاع واضغط «قسّم المضلع». بعد ذلك اختر الإجابات من الرسم، دون كتابة أرقام.",
      questionIds: ["hexagon-triangles", "choose-four-triangle-shape"],
    },
    {
      id: "formula",
      type: "concept",
      eyebrow: "ما اكتشفته للتو",
      title: "نبني القانون",
      body: [
        "عدد المثلثات الناتجة من رأس واحد يساوي عدد الأضلاع ناقص 2.",
        "كل مثلث يضيف 180° إلى مجموع الزوايا الداخلية.",
      ],
      formula: "S = (n - 2) \\times 180^\\circ",
      questionIds: ["formula-order", "heptagon-sum"],
    },
    {
      id: "worked-example",
      type: "worked_example",
      eyebrow: "مثال محلول",
      title: "من المجموع إلى زاوية مجهولة",
      body: [
        "الرباعي مجموع زواياه 360°.",
        "إذا عرفت ثلاث زوايا، اجمعها ثم اطرح الناتج من 360°.",
      ],
      questionIds: ["missing-angle"],
    },
    {
      id: "exterior",
      type: "concept",
      eyebrow: "مفهوم مكمل",
      title: "لفة كاملة حول المضلع",
      body: ["الزوايا الخارجية تمثل مقدار دورانك عند الرؤوس. بعد دورة كاملة يكون مجموع الدوران 360°."],
      formula: "\\sum \\text{الزوايا الخارجية} = 360^\\circ",
      questionIds: ["exterior-sum"],
    },
    {
      id: "teacher-summary",
      type: "teacher_summary",
      eyebrow: "خريطة الدرس",
      title: "ثبّت الخطوات في ذهنك",
      tutorMessage: "هذه خلاصة قصيرة قبل الاختبار. لا توجد أسئلة في هذه الشريحة.",
    },
    {
      id: "assessment",
      type: "assessment",
      eyebrow: "اختبار نهاية الدرس",
      title: "أثبت ما أتقنته",
      questionIds: [
        "assessment-triangle",
        "assessment-octagon-triangles",
        "assessment-dodecagon",
        "assessment-missing-angle",
        "assessment-nonagon-exterior",
      ],
    },
    {
      id: "report",
      type: "report",
      eyebrow: "تقريرك",
      title: "ماذا أتقنت؟ وما الذي تراجعه؟",
    },
  ],
  assessmentQuestionIds: [
    "assessment-triangle",
    "assessment-octagon-triangles",
    "assessment-dodecagon",
    "assessment-missing-angle",
    "assessment-nonagon-exterior",
  ],
  videos: [
    {
      id: "sharaf-polygon-angles-whiteboard",
      title: "شرح شارف الأصلي — سبورة تعليمية",
      url: "/videos/sharaf-polygon-angles/sharaf-polygon-angles-whiteboard.mp4",
      source: "hosted",
      thumbnailUrl: "/videos/sharaf-polygon-angles/sharaf-polygon-angles-poster.jpg",
      captionsUrl: "/videos/sharaf-polygon-angles/sharaf-polygon-angles-whiteboard.ar.vtt",
      channelName: "منصة شارف التعليمية",
      duration: "10:00",
    },
    {
      id: "_l49Ard1--U",
      title: "زوايا المضلع — الجزء الأول",
      url: "https://www.youtube-nocookie.com/embed/_l49Ard1--U?rel=0&modestbranding=1",
      channelName: "منال التويجري رياضيات",
    },
    {
      id: "E-ndz2M-yfM",
      title: "زوايا المضلع — الجزء الثاني",
      url: "https://www.youtube-nocookie.com/embed/E-ndz2M-yfM?rel=0&modestbranding=1",
      channelName: "منال التويجري رياضيات",
    },
    {
      id: "O9-_Yy6l-Ok",
      title: "زوايا المضلع — شرح بديل",
      url: "https://www.youtube-nocookie.com/embed/O9-_Yy6l-Ok?rel=0&modestbranding=1",
      channelName: "محمد الحربي — رياضيات ثانوي",
    },
  ],
  teacherSummary: {
    status: "editorial",
    attribution: "ملخص تعليمي بانتظار اعتماد معلم المادة",
    points: [
      "قسّم المضلع من رأس واحد لتحصل على n - 2 مثلثًا.",
      "مجموع الزوايا الداخلية يساوي (n - 2) × 180°.",
      "لإيجاد زاوية مجهولة، اطرح مجموع الزوايا المعروفة من مجموع زوايا المضلع.",
      "مجموع زاوية خارجية واحدة عند كل رأس يساوي 360°.",
    ],
  },
  tutorKnowledge: {
    approvedFacts: [
      "مجموع زوايا أي مثلث 180 درجة.",
      "تقسيم مضلع ذي n أضلاع من رأس واحد ينتج n - 2 مثلثات.",
      "مجموع الزوايا الداخلية يساوي (n - 2) مضروبًا في 180 درجة.",
      "الخماسي ينقسم إلى 3 مثلثات ومجموع زواياه 540 درجة.",
      "السداسي ينقسم إلى 4 مثلثات ومجموع زواياه 720 درجة.",
      "مجموع زاوية خارجية واحدة عند كل رأس لأي مضلع محدب يساوي 360 درجة.",
    ],
    socraticPrompts: [
      "ما الذي تعرفه عن مجموع زوايا المثلث؟",
      "كم مثلثًا ترى عند التقسيم من رأس واحد؟",
      "ما الفرق بين عدد الأضلاع وعدد المثلثات في الرسم؟",
      "ما الخطوة التي تسبق الضرب في 180؟",
    ],
    outOfScopeReply: "سؤالك خارج هدف درس زوايا المضلع. أستطيع مساعدتك في التقسيم إلى مثلثات، القانون، الزوايا المجهولة، أو الزوايا الخارجية.",
  },
};

export const polygonAnglesQuestionMap = Object.fromEntries(
  polygonAnglesLesson.questions.map((question) => [question.id, question]),
);
