import type { InteractiveLessonDefinition } from "./types";

export const RATIONAL_NUMBERS_LESSON_ID = "m2-1-1";

export const rationalNumbersLesson: InteractiveLessonDefinition = {
  id: RATIONAL_NUMBERS_LESSON_ID,
  version: 1,
  slug: "rational-numbers",
  title: "الأعداد النسبية",
  stage: "المرحلة المتوسطة",
  grade: "الصف الثاني المتوسط",
  subject: "الرياضيات",
  unit: "الأعداد النسبية",
  estimatedMinutes: 25,
  introduction: {
    heading: "الكسر والعشري نقطتان لنفس العدد",
    paragraphs: [
      "العدد النسبي هو كل عدد يمكن كتابته على صورة كسر بسطه ومقامه عددان صحيحان، ومقامه لا يساوي صفرًا. لذلك لا تقتصر الأعداد النسبية على الكسور الظاهرة؛ فالأعداد الصحيحة والأعداد العشرية المنتهية أو الدورية نسبية أيضًا.",
      "مثلًا: العدد −7 نسبي لأنه يكتب −7/1، والعدد 0.75 نسبي لأنه يساوي 3/4. أما المقام فلا يمكن أن يساوي صفرًا لأن القسمة على صفر غير معرفة.",
      "سنربط في هذا الدرس بين ثلاث صور للعدد نفسه: كسر، وعدد عشري، ونقطة على خط الأعداد. عندما ترى الصور الثلاث معًا يصبح التعامل مع الأعداد الموجبة والسالبة أوضح.",
    ],
    foundationSteps: [
      { title: "ابحث عن صورة الكسر", description: "إذا أمكن كتابة العدد a/b مع b ≠ 0 فهو عدد نسبي." },
      { title: "حوّل بالقسمة", description: "لقراءة الكسر عشريًا اقسم البسط على المقام، مع مراعاة الإشارة." },
      { title: "ضعه على الخط", description: "الموجب يمين الصفر، والسالب يساره، والمسافة من الصفر تمثل القيمة المطلقة." },
    ],
    examples: [],
    takeawayLabel: "الفكرة التي تجمع الصور:",
    takeaway: "3/4 و0.75 ونقطة تقع عند ثلاثة أرباع المسافة بين 0 و1 كلها تمثل العدد النسبي نفسه.",
    formula: {
      expression: String.raw`\mathbb{Q}=\left\{\frac{a}{b}: a,b\in\mathbb{Z},\ b\ne0\right\}`,
      label: "مجموعة الأعداد النسبية هي الأعداد التي تكتب على صورة بسط على مقام؛ وكلاهما صحيح والمقام لا يساوي صفرًا",
      eyebrow: "تعريف العدد النسبي",
      heading: "شرطان بسيطان: بسط ومقام صحيحان، والمقام ليس صفرًا",
      parts: [
        { symbol: "a", meaning: "البسط: عدد صحيح موجب أو سالب أو صفر" },
        { symbol: "b", meaning: "المقام: عدد صحيح لا يساوي صفرًا" },
        { symbol: "a/b", meaning: "صورة كسرية تمثل قسمة a على b" },
        { symbol: "Q", meaning: "رمز مجموعة الأعداد النسبية" },
      ],
    },
    workedExample: {
      title: "مثال سريع: حوّل 3/8 إلى عشري",
      steps: ["اقسم البسط 3 على المقام 8", "3 ÷ 8 = 0.375", "التمثيل العشري انتهى، وهذا يؤكد أنه نسبي"],
      result: "3/8 = 0.375",
    },
    commonMistake: {
      wrong: "5/0 عدد نسبي",
      correction: "وجود خط كسر لا يكفي؛ يجب ألا يساوي المقام صفرًا لأن القسمة على صفر غير معرفة.",
    },
  },
  objectives: [
    "أتعرف العدد النسبي من تعريفه وصوره المختلفة.",
    "أحوّل بين الكسر الاعتيادي والعدد العشري.",
    "أمثل عددًا نسبيًا على خط الأعداد.",
    "أربط العدد السالب بمعكوسه الجمعي وقيمته المطلقة.",
  ],
  skills: [
    { id: "rational-definition", title: "تعريف العدد النسبي", shortTitle: "هل هو نسبي؟", description: "يتحقق من إمكانية كتابة العدد على صورة كسر بسطه ومقامه صحيحان ومقامه غير صفري." },
    { id: "fraction-to-decimal", title: "تحويل الكسر إلى عشري", shortTitle: "كسر إلى عشري", description: "يقسم البسط على المقام مع المحافظة على الإشارة." },
    { id: "decimal-to-fraction", title: "تحويل العشري إلى كسر", shortTitle: "عشري إلى كسر", description: "يكتب العشري المنتهي على مقام من قوى العشرة ثم يبسطه." },
    { id: "number-line", title: "التمثيل على خط الأعداد", shortTitle: "خط الأعداد", description: "يرتب الأعداد النسبية بحسب مواقعها من اليسار إلى اليمين." },
    { id: "absolute-opposite", title: "المعكوس والقيمة المطلقة", shortTitle: "المسافة من الصفر", description: "يميز بين إشارة العدد ومسافته غير السالبة من الصفر." },
  ],
  questions: [
    {
      id: "rational-negative-integer",
      skillId: "rational-definition",
      type: "true_false",
      prompt: "العدد −7 عدد نسبي؛ لأنه يمكن كتابته على صورة −7/1.",
      options: [{ id: "true", label: "صح" }, { id: "false", label: "خطأ" }],
      correctAnswer: true,
      hints: [],
      correctFeedback: "صحيح. كل عدد صحيح نسبي لأننا نستطيع وضعه فوق المقام 1.",
      defaultIncorrectFeedback: "اختبر شرطي التعريف: −7 و1 صحيحان، والمقام 1 لا يساوي صفرًا.",
    },
    {
      id: "rational-three-eighths",
      skillId: "fraction-to-decimal",
      type: "multiple_choice",
      prompt: "ما الصورة العشرية للكسر 3/8؟",
      options: [{ id: "0375", label: "0.375" }, { id: "038", label: "0.38" }, { id: "266", label: "2.666…" }, { id: "024", label: "0.24" }],
      correctAnswer: "0375",
      hints: [],
      correctFeedback: "صحيح. 3 ÷ 8 = 0.375.",
      defaultIncorrectFeedback: "حوّل الكسر إلى عملية قسمة: البسط 3 مقسومًا على المقام 8.",
    },
    {
      id: "rational-negative-decimal",
      skillId: "decimal-to-fraction",
      type: "multiple_choice",
      prompt: "أي كسر في أبسط صورة يساوي −1.25؟",
      options: [{ id: "minus-five-fourths", label: "−5/4" }, { id: "minus-one-fourth", label: "−1/4" }, { id: "five-fourths", label: "5/4" }, { id: "minus-125-tenths", label: "−125/10" }],
      correctAnswer: "minus-five-fourths",
      hints: [],
      correctFeedback: "صحيح. −1.25 = −125/100، وبعد القسمة على 25 نحصل على −5/4.",
      defaultIncorrectFeedback: "اكتب −1.25 على صورة −125/100، ثم بسط البسط والمقام بالقاسم المشترك الأكبر.",
      errorPatterns: [{ answers: ["five-fourths"], feedback: "القيمة صحيحة لكن الإشارة فُقدت. العدد الأصلي سالب." }, { answers: ["minus-125-tenths"], feedback: "منزلتان عشريتان تعنيان مقامًا 100 لا 10، ثم نحتاج إلى التبسيط." }],
    },
    {
      id: "rational-order-line",
      skillId: "number-line",
      type: "ordering",
      prompt: "رتّب الأعداد من الأصغر إلى الأكبر كما تظهر من اليسار إلى اليمين على خط الأعداد.",
      options: [{ id: "minus-three-halves", label: "−3/2" }, { id: "minus-half", label: "−1/2" }, { id: "quarter", label: "1/4" }],
      correctAnswer: ["minus-three-halves", "minus-half", "quarter"],
      hints: [],
      correctFeedback: "ممتاز. −1.5 يقع أبعد يسارًا من −0.5، ثم يأتي 0.25 يمين الصفر.",
      defaultIncorrectFeedback: "حوّلها ذهنيًا إلى −1.5 و−0.5 و0.25، ثم اقرأ خط الأعداد من اليسار إلى اليمين.",
    },
    {
      id: "rational-absolute-value",
      skillId: "absolute-opposite",
      type: "multiple_choice",
      prompt: "ما قيمة |−2/3|؟",
      options: [{ id: "positive", label: "2/3" }, { id: "negative", label: "−2/3" }, { id: "zero", label: "0" }, { id: "three-halves", label: "3/2" }],
      correctAnswer: "positive",
      hints: [],
      correctFeedback: "صحيح. القيمة المطلقة هي المسافة من الصفر، والمسافة لا تكون سالبة.",
      defaultIncorrectFeedback: "لا تبحث عن الإشارة؛ اسأل عن المسافة بين −2/3 والصفر.",
    },
  ],
  steps: [
    { id: "objectives", type: "objectives", eyebrow: "1. شرح الدرس", title: "افهم معنى العدد النسبي من ثلاث صور", tutorMessage: "سنربط الكسر بالعشري وخط الأعداد حتى لا يبقى التعريف كلامًا مجردًا." },
    { id: "official-book", type: "official_book", eyebrow: "2. كتاب الوزارة", title: "راجع الدرس من المصدر الرسمي", tutorMessage: "استخدم الكتاب مرجعًا، ثم عد إلى الأنشطة التي تحول الأمثلة إلى حركة." },
    { id: "video", type: "video", eyebrow: "3. الشرح المرئي", title: "شاهد شرحًا بديلًا للمفهوم", tutorMessage: "ركّز على كيف يتحول الكسر إلى عدد عشري، وكيف تظهر الإشارة على خط الأعداد." },
    { id: "number-line", type: "concept", eyebrow: "4. خط الأعداد", title: "حرّك النقطة بين السالب والموجب", visualKind: "rational-number-line", body: ["كلما تحركنا يمينًا زادت قيمة العدد.", "العددان المتعاكسان يبعدان المسافة نفسها عن الصفر."] },
    { id: "fraction-decimal", type: "concept", eyebrow: "5. آلة التحويل", title: "شاهد الكسر يتحول إلى عشري خطوة خطوة", visualKind: "fraction-decimal-machine", body: ["البسط ÷ المقام يعطينا الصورة العشرية.", "العشري المنتهي يمكن إعادته إلى كسر مقامه 10 أو 100 أو 1000 ثم تبسيطه."] },
    { id: "signs", type: "worked_example", eyebrow: "6. الإشارة والمسافة", title: "فرّق بين المعكوس والقيمة المطلقة", body: ["معكوس 3/4 الجمعي هو −3/4، ومجموعهما صفر.", "|−3/4| = 3/4 لأنها تمثل المسافة من الصفر.", "السالب يخبرنا بالاتجاه، والقيمة المطلقة تخبرنا بالمسافة."] },
    { id: "definition-check", type: "concept", eyebrow: "7. مفهوم مكمل", title: "لماذا المقام لا يساوي صفرًا؟", body: ["خط الكسر يعني قسمة البسط على المقام.", "القسمة على صفر غير معرفة، لذلك لا يمثل كسر مقامه صفر عددًا نسبيًا.", "الصفر نفسه عدد نسبي لأنه يكتب 0/1."] },
    { id: "teacher-summary", type: "teacher_summary", eyebrow: "8. خريطة الدرس", title: "ثبّت الصور الثلاث قبل الاختبار" },
    { id: "assessment", type: "assessment", eyebrow: "9. اختبار الدرس", title: "طبّق بخمس مهام متنوعة", questionIds: ["rational-negative-integer", "rational-three-eighths", "rational-negative-decimal", "rational-order-line", "rational-absolute-value"] },
    { id: "report", type: "report", eyebrow: "10. تقريرك", title: "ماذا أتقنت وماذا تراجع؟" },
  ],
  assessmentQuestionIds: ["rational-negative-integer", "rational-three-eighths", "rational-negative-decimal", "rational-order-line", "rational-absolute-value"],
  videos: [{ id: "D-CZClQ_jlo", title: "الأعداد النسبية — رياضيات ثاني متوسط", url: "https://www.youtube-nocookie.com/embed/D-CZClQ_jlo", source: "youtube", channelName: "رياضيات ابتدائي ومتوسط — شرح عبدالله القرني" }],
  curriculumSource: {
    authority: "وزارة التعليم السعودية — بوابة مدرستي",
    portalUrl: "https://madrasatibeta.moe.gov.sa/books/B47494BFDA4FEA2A30BBC9FC72357528?Language=1",
    bookTitle: "الرياضيات — الصف الثاني المتوسط — الجزء الأول",
    requiredEdition: "النسخة المنشورة حاليًا في بوابة مدرستي",
    editionStatus: "verified",
    observedEdition: "النسخة الرسمية المتاحة للعام 1447–1448هـ / 2025–2026م",
    editionEvidence: "تم التحقق من صفحة كتاب الرياضيات للصف الثاني المتوسط في بوابة مدرستي الرسمية.",
    checkedAt: "2026-09-01",
    verifiedAt: "2026-09-01",
  },
  teacherSummary: {
    status: "editorial",
    attribution: "ملخص تحريري مطابق لسياق الدرس الرسمي — بانتظار اعتماد معلم مادة قبل Production.",
    points: ["العدد النسبي يكتب كسرًا بسطه ومقامه صحيحان ومقامه غير صفري.", "كل عدد صحيح نسبي لأنه يكتب على مقام 1.", "لتحويل الكسر إلى عشري نقسم البسط على المقام.", "العشري المنتهي يكتب كسرًا على قوة من قوى 10 ثم يبسط.", "القيمة المطلقة مسافة غير سالبة من الصفر."],
  },
  tutorKnowledge: {
    approvedFacts: [
      "العدد النسبي يمكن كتابته كسرًا بسطه ومقامه عددان صحيحان ومقامه لا يساوي صفرًا.",
      "كل عدد صحيح عدد نسبي لأنه يمكن كتابته على مقام 1.",
      "الكسر 3/8 يساوي العدد العشري 0.375.",
      "العدد العشري المنتهي يمكن كتابته كسرًا مقامه قوة من قوى 10 ثم تبسيطه.",
      "على خط الأعداد تزداد القيم باتجاه اليمين.",
      "القيمة المطلقة هي المسافة من الصفر ولذلك لا تكون سالبة.",
      "معكوس العدد الجمعي له القيمة المطلقة نفسها والإشارة المعاكسة، ومجموع العدد ومعكوسه صفر.",
      "القسمة على صفر غير معرفة، لذلك a/0 ليس عددًا نسبيًا.",
    ],
    socraticPrompts: ["هل تستطيع كتابة العدد على صورة كسر مقامه لا يساوي صفرًا؟", "ما العملية التي يحكيها خط الكسر؟", "أين يقع العدد بالنسبة إلى الصفر؟", "كم منزلة عشرية ترى، وما المقام المناسب؟"],
    outOfScopeReply: "أنا معك الآن في درس الأعداد النسبية. اسألني عن تعريفها، التحويل بين الكسر والعشري، خط الأعداد، الإشارة أو القيمة المطلقة.",
  },
};

export const rationalNumbersQuestionMap = Object.fromEntries(
  rationalNumbersLesson.questions.map((question) => [question.id, question]),
);
