import type { InteractiveLessonDefinition } from "./types";

export const REAL_NUMBER_PROPERTIES_LESSON_ID = "h2-1-1";

export const realNumberPropertiesLesson: InteractiveLessonDefinition = {
  id: REAL_NUMBER_PROPERTIES_LESSON_ID,
  version: 1,
  slug: "real-number-properties",
  title: "خصائص الأعداد الحقيقية",
  stage: "المرحلة الثانوية",
  grade: "الصف الثاني الثانوي",
  subject: "الرياضيات 2-1",
  unit: "الدوال والمتباينات",
  estimatedMinutes: 28,
  introduction: {
    heading: "خريطة واحدة تنظّم كل الأعداد التي تعرفها",
    paragraphs: [
      "الأعداد الحقيقية ليست نوعًا جديدًا من الأعداد، بل عائلة كبيرة تجمع الأعداد النسبية وغير النسبية. وداخل الأعداد النسبية نجد الأعداد الصحيحة، وداخل الصحيحة نجد الكلية، وداخل الكلية نجد الطبيعية.",
      "الفكرة المهمة ليست حفظ الرموز فقط، بل معرفة مكان كل عدد ولماذا يمكن أن ينتمي إلى أكثر من مجموعة. فالعدد 5 طبيعي، وكلي، وصحيح، ونسبي، وحقيقي في الوقت نفسه.",
      "بعد بناء خريطة المجموعات سنفهم كيف تساعدنا خصائص الجمع والضرب — التبديلية والتجميعية والتوزيعية — على إعادة كتابة العبارات دون تغيير قيمتها.",
    ],
    foundationSteps: [
      { title: "صنّف شكل العدد", description: "العدد الصحيح يمكن كتابته على صورة كسر مقامه 1، لذلك كل عدد صحيح هو عدد نسبي أيضًا." },
      { title: "راقب التمثيل العشري", description: "العشري المنتهي أو الدوري نسبي، أمّا غير المنتهي وغير الدوري مثل √2 فهو غير نسبي." },
      { title: "اختر الخاصية المناسبة", description: "التبديلية تغيّر الترتيب، والتجميعية تغيّر الأقواس، والتوزيعية تنشر الضرب على ما داخل القوس." },
    ],
    examples: [],
    takeawayLabel: "الخريطة المختصرة:",
    takeaway: "الطبيعية ⊂ الكلية ⊂ الصحيحة ⊂ النسبية ⊂ الحقيقية، بينما غير النسبية فرع آخر داخل الحقيقية لا يتقاطع مع النسبية.",
    formula: {
      expression: String.raw`\mathbb{N} \subset \mathbb{W} \subset \mathbb{Z} \subset \mathbb{Q} \subset \mathbb{R}`,
      label: "الأعداد الطبيعية مجموعة جزئية من الكلية، والكلية من الصحيحة، والصحيحة من النسبية، والنسبية من الحقيقية",
      eyebrow: "خريطة المجموعات",
      heading: "كل صندوق يوجد داخل الصندوق الأكبر منه",
      parts: [
        { symbol: "N", meaning: "الأعداد الطبيعية: 1، 2، 3، …" },
        { symbol: "W", meaning: "الأعداد الكلية: الطبيعية ومعها الصفر" },
        { symbol: "Z", meaning: "الأعداد الصحيحة: السالبة والصفر والموجبة" },
        { symbol: "Q", meaning: "الأعداد النسبية التي تكتب على صورة a/b حيث b ≠ 0" },
        { symbol: "I", meaning: "الأعداد غير النسبية مثل √2 وπ" },
        { symbol: "R", meaning: "جميع الأعداد النسبية وغير النسبية" },
      ],
    },
    workedExample: {
      title: "مثال سريع: أين يقع العدد −8؟",
      steps: ["−8 ليس طبيعيًا ولا كليًا لأنه سالب", "هو عدد صحيح", "يمكن كتابته −8/1، إذن هو نسبي", "كل عدد نسبي هو عدد حقيقي"],
      result: "−8 ينتمي إلى Z وQ وR",
    },
    commonMistake: {
      wrong: "√9 عدد غير نسبي",
      correction: "لا نحكم من وجود رمز الجذر وحده. بما أن √9 = 3، فهو طبيعي وكلي وصحيح ونسبي وحقيقي.",
    },
  },
  objectives: [
    "أصنّف العدد في جميع المجموعات التي ينتمي إليها.",
    "أميّز العدد النسبي من غير النسبي من تمثيله.",
    "أتعرف خصائص الجمع والضرب وأربط كل خاصية بشكلها.",
    "أستعمل الخصائص لإعادة كتابة العبارات وتبسيطها.",
  ],
  skills: [
    { id: "number-sets", title: "تصنيف مجموعات الأعداد", shortTitle: "خريطة الأعداد", description: "يحدد جميع المجموعات التي ينتمي إليها العدد." },
    { id: "rational-irrational", title: "النسبي وغير النسبي", shortTitle: "نسبي أم غير نسبي", description: "يميز العدد النسبي من شكل الكسر أو التمثيل العشري أو الجذر." },
    { id: "operation-properties", title: "خصائص العمليات", shortTitle: "اسم الخاصية", description: "يميز التبديلية والتجميعية والعنصر المحايد والنظير." },
    { id: "apply-properties", title: "تطبيق الخصائص", shortTitle: "استخدام الخصائص", description: "يستعمل التوزيعية وخصائص العمليات لإعادة كتابة تعبير مكافئ." },
    { id: "radical-form", title: "الصورة المبسطة للجذر", shortTitle: "الجذور", description: "يتحقق من قيمة الجذر ويميز الجذر النسبي من غير النسبي." },
  ],
  questions: [
    {
      id: "real-set-negative-eight",
      skillId: "number-sets",
      type: "multiple_choice",
      prompt: "أي خيار يذكر جميع المجموعات التي ينتمي إليها العدد −8؟",
      options: [
        { id: "zqr", label: "الصحيحة Z، والنسبية Q، والحقيقية R" },
        { id: "n-w-z", label: "الطبيعية N، والكلية W، والصحيحة Z" },
        { id: "i-r", label: "غير النسبية I، والحقيقية R" },
        { id: "q-only", label: "النسبية Q فقط" },
      ],
      correctAnswer: "zqr",
      hints: [],
      correctFeedback: "صحيح. −8 عدد صحيح، ويمكن كتابته −8/1 فيكون نسبيًا، وكل نسبي حقيقي.",
      defaultIncorrectFeedback: "ابدأ بأصغر مجموعة ينتمي إليها −8 ثم تحرك إلى الصناديق الأكبر. العدد السالب ليس طبيعيًا ولا كليًا.",
      errorPatterns: [
        { answers: ["n-w-z"], feedback: "الأعداد الطبيعية والكلية لا تشمل الأعداد السالبة." },
        { answers: ["i-r"], feedback: "−8 = −8/1، لذلك هو نسبي وليس غير نسبي." },
        { answers: ["q-only"], feedback: "هو نسبي فعلًا، لكنه أيضًا عدد صحيح وحقيقي؛ المطلوب جميع المجموعات." },
      ],
    },
    {
      id: "real-sqrt-eleven",
      skillId: "rational-irrational",
      type: "true_false",
      prompt: "√11 عدد غير نسبي؛ لأن 11 ليس مربعًا كاملًا.",
      options: [{ id: "true", label: "صح" }, { id: "false", label: "خطأ" }],
      correctAnswer: true,
      hints: [],
      correctFeedback: "صحيح. تمثيل √11 العشري غير منتهٍ وغير دوري، لذلك هو غير نسبي وحقيقي.",
      defaultIncorrectFeedback: "قارن 11 بالمربعات الكاملة القريبة: 9 و16. لا ينتج عن جذره عدد صحيح أو كسر نسبي.",
    },
    {
      id: "real-commutative-property",
      skillId: "operation-properties",
      type: "multiple_choice",
      prompt: "ما الخاصية الموضحة في 7 + 12 = 12 + 7؟",
      options: [
        { id: "commutative", label: "خاصية التبديل للجمع" },
        { id: "associative", label: "خاصية التجميع للجمع" },
        { id: "identity", label: "خاصية العنصر المحايد" },
        { id: "distributive", label: "خاصية التوزيع" },
      ],
      correctAnswer: "commutative",
      hints: [],
      correctFeedback: "صحيح. تغير ترتيب العددين فقط، ولم تتغير الأقواس؛ إذن هي خاصية التبديل.",
      defaultIncorrectFeedback: "راقب ما تغيّر: العددان نفسهما لكن مكانيهما تبدلا. هذا يحدد اسم الخاصية.",
    },
    {
      id: "real-distribute-order",
      skillId: "apply-properties",
      type: "ordering",
      prompt: "رتّب البطاقات لتبسيط 4(2x + 3) باستعمال خاصية التوزيع.",
      options: [
        { id: "multiply-first", label: "اضرب 4 في 2x، واضرب 4 في 3" },
        { id: "products", label: "اكتب 8x + 12" },
        { id: "equivalent", label: "تأكد أن التعبير الجديد مكافئ للأصلي" },
      ],
      correctAnswer: ["multiply-first", "products", "equivalent"],
      hints: [],
      correctFeedback: "ممتاز. وزّعت 4 على كل حد داخل القوس فحصلت على التعبير المكافئ 8x + 12.",
      defaultIncorrectFeedback: "في التوزيع يجب أن يصل العامل خارج القوس إلى كل حد داخله قبل كتابة الناتج.",
    },
    {
      id: "real-perfect-root",
      skillId: "radical-form",
      type: "multiple_choice",
      prompt: "أي عبارة صحيحة عن √49؟",
      options: [
        { id: "natural-chain", label: "يساوي 7؛ لذلك هو طبيعي وكلي وصحيح ونسبي وحقيقي" },
        { id: "irrational", label: "غير نسبي لأن عليه رمز جذر" },
        { id: "integer-only", label: "صحيح فقط ولا ينتمي إلى النسبية" },
        { id: "negative", label: "يساوي −7 فقط" },
      ],
      correctAnswer: "natural-chain",
      hints: [],
      correctFeedback: "صحيح. √49 هو الجذر التربيعي الرئيس الموجب ويساوي 7، ثم نتبعه عبر خريطة المجموعات.",
      defaultIncorrectFeedback: "احسب الجذر أولًا قبل تصنيف العدد. وجود رمز الجذر لا يعني تلقائيًا أن العدد غير نسبي.",
    },
  ],
  steps: [
    { id: "objectives", type: "objectives", eyebrow: "1. شرح الدرس", title: "ابنِ خريطة الأعداد قبل حفظ الرموز", tutorMessage: "سأريك كيف تصبح مجموعات الأعداد صناديق متداخلة، ثم نستخدم الخصائص لتحريك العبارات بأمان." },
    { id: "official-book", type: "official_book", eyebrow: "2. كتاب الوزارة", title: "راجع الدرس من مصدره الرسمي", tutorMessage: "هذا هو مرجع المنهج المعتمد. افتحه عند الحاجة ثم عد إلى التجربة التفاعلية." },
    { id: "video", type: "video", eyebrow: "3. الشرح المرئي", title: "اختر المعلم الذي يناسبك", tutorMessage: "ابدأ بالشرح الأول، وإن لم يناسبك أسلوبه فانتقل إلى الشرح الآخر." },
    { id: "number-sets", type: "concept", eyebrow: "4. خريطة المجموعات", title: "حرّك عددًا وشاهد جميع الصناديق التي تحتويه", visualKind: "real-number-sets", body: ["قد ينتمي العدد إلى أكثر من مجموعة في الوقت نفسه.", "ابدأ بأصغر مجموعة، ثم اتبع الاحتواء إلى الحقيقية R."] },
    { id: "decimal-patterns", type: "concept", eyebrow: "5. بصمة العدد", title: "التمثيل العشري يكشف النسبي وغير النسبي", visualKind: "real-number-decimals", body: ["العشري المنتهي أو الدوري يمكن كتابته على صورة كسر.", "العشري غير المنتهي وغير الدوري يمثل عددًا غير نسبي."] },
    { id: "operation-properties", type: "worked_example", eyebrow: "6. مختبر الخصائص", title: "غيّر الترتيب أو الأقواس دون تغيير القيمة", visualKind: "real-number-properties", body: ["التبديلية تغيّر ترتيب عددين في الجمع أو الضرب.", "التجميعية تغيّر موضع الأقواس، والتوزيعية تربط الضرب بالجمع."] },
    { id: "radicals", type: "concept", eyebrow: "7. مفهوم مكمل", title: "لا تحكم على الجذر من شكله", body: ["إذا كان ما تحت الجذر مربعًا كاملًا مثل 49 فإن الجذر عدد صحيح.", "إذا لم يكن مربعًا كاملًا مثل 11 فإن جذره غير نسبي.", "الجذر التربيعي الرئيس لعدد موجب هو الجذر غير السالب."] },
    { id: "teacher-summary", type: "teacher_summary", eyebrow: "8. خريطة الدرس", title: "ثبّت الفكرة قبل الاختبار" },
    { id: "assessment", type: "assessment", eyebrow: "9. اختبار الدرس", title: "اختبر فهمك بخمس مهام متنوعة", questionIds: ["real-set-negative-eight", "real-sqrt-eleven", "real-commutative-property", "real-distribute-order", "real-perfect-root"] },
    { id: "report", type: "report", eyebrow: "10. تقريرك", title: "ماذا أتقنت وماذا تراجع؟" },
  ],
  assessmentQuestionIds: ["real-set-negative-eight", "real-sqrt-eleven", "real-commutative-property", "real-distribute-order", "real-perfect-root"],
  videos: [
    {
      id: "kIF3GJu3DGc",
      title: "خصائص الأعداد الحقيقية | رياضيات 2-1",
      url: "https://www.youtube-nocookie.com/embed/kIF3GJu3DGc",
      source: "youtube",
      channelName: "محمد الحربي — رياضيات ثانوي",
      duration: "نحو 22 دقيقة",
    },
    {
      id: "0jMc5S8v_3s",
      title: "خصائص الأعداد الحقيقية — شرح وتطبيق",
      url: "https://www.youtube-nocookie.com/embed/0jMc5S8v_3s",
      source: "youtube",
      channelName: "شرح المنهج السعودي",
    },
  ],
  curriculumSource: {
    authority: "وزارة التعليم السعودية — بوابة مدرستي",
    portalUrl: "https://madrasatibeta.moe.gov.sa/books/3B7E33BCAA9DCFEE8ECBD670A0C2D6DA?Language=1",
    bookTitle: "الرياضيات 2-1 — السنة الثانية — نظام المسارات",
    requiredEdition: "النسخة المنشورة حاليًا في بوابة مدرستي",
    editionStatus: "verified",
    observedEdition: "النسخة الرسمية المتاحة للعام 1447–1448هـ / 2025–2026م",
    editionEvidence: "تم التحقق من صفحة الصف الثاني الثانوي — المسار العام في بوابة مدرستي الرسمية.",
    checkedAt: "2026-09-01",
    verifiedAt: "2026-09-01",
  },
  teacherSummary: {
    status: "editorial",
    attribution: "ملخص تحريري مطابق لسياق الدرس الرسمي — بانتظار اعتماد معلم مادة قبل Production.",
    points: [
      "N داخل W داخل Z داخل Q داخل R.",
      "غير النسبية I والحقيقية R: غير النسبي حقيقي لكنه ليس نسبيًا.",
      "العشري المنتهي أو الدوري نسبي؛ وغير المنتهي وغير الدوري غير نسبي.",
      "التبديلية تغيّر الترتيب، والتجميعية تغيّر الأقواس، والتوزيعية تضرب كل حد داخل القوس.",
      "احسب قيمة الجذر أولًا، ثم صنّف الناتج بدل الحكم من رمز الجذر.",
    ],
  },
  tutorKnowledge: {
    approvedFacts: [
      "الأعداد الحقيقية R تتكون من الأعداد النسبية Q والأعداد غير النسبية I.",
      "الأعداد الطبيعية N مجموعة جزئية من الكلية W، والكلية من الصحيحة Z، والصحيحة من النسبية Q، والنسبية من الحقيقية R.",
      "كل عدد نسبي يمكن كتابته على صورة a/b حيث a وb عددان صحيحان وb لا يساوي صفرًا.",
      "التمثيل العشري للعدد النسبي منتهٍ أو دوري، وتمثيل العدد غير النسبي غير منتهٍ وغير دوري.",
      "√49 = 7 عدد طبيعي ونسبي، بينما √11 غير نسبي لأن 11 ليس مربعًا كاملًا.",
      "خاصية التبديل تغيّر ترتيب الحدود، وخاصية التجميع تغيّر موضع الأقواس، وخاصية التوزيع تضرب العامل في كل حد داخل القوس.",
      "الطرح والقسمة لا يحققان خاصية التبديل عمومًا.",
    ],
    socraticPrompts: [
      "هل تستطيع كتابة العدد على صورة كسر مقامه لا يساوي صفرًا؟",
      "ما أصغر مجموعة ينتمي إليها العدد، وما الصناديق الأكبر التي تحتويها؟",
      "هل تغير ترتيب الأعداد أم تغير موضع الأقواس؟",
      "هل العدد تحت الجذر مربع كامل؟",
    ],
    outOfScopeReply: "أنا معك الآن في درس خصائص الأعداد الحقيقية. اسألني عن مجموعات الأعداد، النسبي وغير النسبي، خصائص العمليات، أو الجذور في هذا الدرس.",
  },
};

export const realNumberPropertiesQuestionMap = Object.fromEntries(
  realNumberPropertiesLesson.questions.map((question) => [question.id, question]),
);
