import assert from "node:assert/strict";
import { polygonAnglesLesson } from "../shared/lesson-engine/polygon-angles";
const origin = "http://127.0.0.1:5106";
let cookie = "";
async function call(path: string, body?: unknown, expected = 200, anonymous = false) {
  const response = await fetch(origin + path, { headers: { ...(anonymous ? {} : { Cookie: cookie }), ...(body ? { "Content-Type": "application/json" } : {}) }, ...(body ? { method: "POST", body: JSON.stringify(body) } : {}) });
  assert.equal(response.status, expected, `${path}: ${await (response.status === expected ? Promise.resolve("") : response.text())}`);
  const setCookie = response.headers.get("set-cookie"); if (setCookie && !anonymous) cookie = setCookie.split(";")[0];
  const type = response.headers.get("content-type") ?? "";
  return type.includes("application/json") ? await response.json() : await response.text();
}
await call("/api/admin/lesson-publications", undefined, 401, true);
await call("/api/auth/login", { email: "readiness-student@example.test", password: "Local-Readiness-2026!" });
await call("/api/admin/lesson-publications", undefined, 403);
await call("/api/auth/login", { email: "readiness-editor@example.test", password: "Local-Readiness-2026!" });
const lessons = await call("/api/admin/lesson-publications");
const target = lessons.find((l: any) => !l.published && l.path.includes("الرياضيات") && l.path.includes("أول ثانوي"));
assert.ok(target, "Existing unpublished lesson is required in isolated curriculum");
const item = await call(`/api/admin/lesson-publications/${target.id}?profile=math`);
const initialRevision = item.revision;
const path = `/lesson/secondary/math/${target.id}`;
const before = await call("/sitemap.xml");
assert.ok(!before.includes(target.id));
await call(`/api/public/lesson-package/${target.id}`, undefined, 404);
await call(`/api/admin/lesson-publications/${target.id}`, { action: "publish", revision: initialRevision, draft: item.template, reviewed: true }, 422);
await call(`/api/admin/lesson-publications/${target.id}`, { action: "draft", revision: initialRevision, draft: item.template });
assert.ok((await call("/api/seo?path=" + encodeURIComponent(path))).robots.startsWith("noindex"));
assert.ok(!(await call("/sitemap.xml")).includes(target.id));
const complete = structuredClone(polygonAnglesLesson);
complete.id = target.id; complete.title = target.title;
await call(`/api/admin/lesson-publications/${target.id}`, { action: "publish", revision: initialRevision + 1, draft: complete, reviewed: false }, 400);
const approved = await call(`/api/admin/lesson-publications/${target.id}`, { action: "publish", revision: initialRevision + 1, draft: complete, reviewed: true });
assert.equal(approved.published, true);
assert.equal((await call(`/api/public/lesson-package/${target.id}`)).lesson.title, target.title);
const seo = await call("/api/seo?path=" + encodeURIComponent(path));
assert.ok(seo.robots.startsWith("index")); assert.ok(seo.sections.length);
assert.ok((await call(path)).includes("LearningResource"));
assert.ok((await call("/sitemap.xml")).includes(target.id), "Publishing updates content, HTML SEO and sitemap atomically");
await call(`/api/admin/lesson-publications/${target.id}`, { action: "draft", revision: approved.revision, draft: item.template });
assert.equal((await call(`/api/public/lesson-package/${target.id}`)).lesson.title, target.title, "Draft saves cannot replace published content");
await call(`/api/admin/lesson-publications/${target.id}`, { action: "publish", revision: approved.revision, draft: complete, reviewed: true }, 409);
const withdrawn = await call(`/api/admin/lesson-publications/${target.id}`, { action: "withdraw", revision: approved.revision + 1 });
assert.equal(withdrawn.published, false);
assert.ok((await call("/api/seo?path=" + encodeURIComponent(path))).robots.startsWith("noindex"));
assert.ok(!(await call("/sitemap.xml")).includes(target.id));
await call(`/api/public/lesson-package/${target.id}`, undefined, 404);
assert.ok((await call("/sitemap.xml")).includes(polygonAnglesLesson.id), "Unrelated production seed is preserved");
console.log("PASS isolated API journey: admin protection, empty-draft rejection, approved publishing, immediate content/SEO/sitemap, draft isolation, concurrency conflict, recoverable withdrawal.");
